stages:
  - build
  - run

variables:
  APP_NAME: ${CI_PROJECT_NAME}
  APP_VERSION: "1.0.0"
  S3_BUCKET: "manual-eb"
  AWS_ID: ${AWS_ID}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_REGION: us-east-1
  AWS_PLATFORM: node.js-16

create_eb_version:
  stage: build
  image: python:latest
  allow_failure: false
  script: |
    pip install awscli
    
    echo "Creating zip file"
    git archive -v -o ${APP_NAME}.zip --format=zip HEAD
    
    echo "Creating AWS Version Label"
    AWS_VERSION_LABEL=${APP_NAME}-${APP_VERSION}-${CI_PIPELINE_ID}
    S3_KEY="$AWS_VERSION_LABEL.zip"
    
    echo "Uploading to S3"
    aws s3 cp ${APP_NAME}.zip s3://${S3_BUCKET}/${S3_KEY} --region ${AWS_REGION}
    
    aws elasticbeanstalk create-application-version \
      --application-name ${APP_NAME} \
      --version-label ${AWS_VERSION_LABEL} \
      --region ${AWS_REGION} \
      --source-bundle S3Bucket=${S3_BUCKET},S3Key=${S3_KEY} \
      --description "${CI_COMMIT_DESCRIPTION}" \
      --auto-create-application \

  only:
    refs:
      - main
deploy_aws_eb:
  stage: run
  image: coxauto/aws-ebcli
  when: manual
  script: |
    AWS_VERSION_LABEL=${APP_NAME}-${APP_VERSION}-${CI_PIPELINE_ID}
    
    echo "Deploying app"
    echo n | eb init -i ${APP_NAME} -p ${AWS_PLATFORM} --region ${AWS_REGION}
    eb deploy ${APP_NAME} --version ${AWS_VERSION_LABEL}
  only:
    refs:
      - main